"""
Simple Flask server that mimics the behavior of the agent.py but without
requiring the Strands library.
"""
from flask import Flask, request, jsonify
from pydantic import BaseModel
from typing import List, Dict, Any

# --- Pydantic schema for incoming form ---
class PreferenceForm(BaseModel):
    name: str
    age: int
    height_cm: int
    weight_kg: float
    activity_level: str  # sedentary, light, moderate, active
    dietary_restrictions: List[str] = []  # e.g. ["vegetarian", "gluten-free"]
    dislikes: List[str] = []
    caloric_goal: int = None  # optional explicit calorie target
    goal: str  # e.g. "lose_weight", "gain_muscle", "maintain"

app = Flask(__name__)

@app.route("/plan", methods=["POST"])
def plan_meals():
    # Parse JSON body
    try:
        data = request.get_json()
        if data is None:
            return jsonify({"error": "Invalid or missing JSON data"}), 400
            
        # Validate the data with Pydantic
        form = PreferenceForm(**data)
        
        # Create a mock meal plan
        mock_plan = generate_mock_meal_plan(form)
        
        return jsonify({
            "status": "ok", 
            "plan": mock_plan
        })
    except Exception as e:
        return jsonify({
            "status": "error",
            "message": f"Error processing request: {str(e)}"
        }), 500

def generate_mock_meal_plan(form: PreferenceForm) -> Dict[str, Any]:
    """
    Generate a mock meal plan for demonstration purposes.
    In the real system, this would be generated by the Strands agents.
    """
    # Calculate mock caloric target
    if form.caloric_goal:
        caloric_target = form.caloric_goal
    else:
        # Simple calculation based on weight, height, age, and activity level
        activity_multiplier = {
            "sedentary": 1.2,
            "light": 1.375,
            "moderate": 1.55,
            "active": 1.725
        }.get(form.activity_level.lower(), 1.2)
        
        # BMR using Harris-Benedict equation
        if form.goal == "lose_weight":
            caloric_target = int((10 * form.weight_kg + 6.25 * form.height_cm - 5 * form.age + 5) * activity_multiplier * 0.85)
        elif form.goal == "gain_muscle":
            caloric_target = int((10 * form.weight_kg + 6.25 * form.height_cm - 5 * form.age + 5) * activity_multiplier * 1.1)
        else:  # maintain
            caloric_target = int((10 * form.weight_kg + 6.25 * form.height_cm - 5 * form.age + 5) * activity_multiplier)
    
    # Create a simple meal plan structure for 7 days
    meal_plan = {}
    for day in ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]:
        meal_plan[day] = {
            "breakfast": {
                "meal": "Protein oatmeal with fruits",
                "calories": 350,
                "protein": 20,
                "carbs": 45,
                "fat": 10
            },
            "lunch": {
                "meal": "Grilled chicken salad with avocado",
                "calories": 450,
                "protein": 35,
                "carbs": 15,
                "fat": 25
            },
            "dinner": {
                "meal": "Baked salmon with roasted vegetables",
                "calories": 550,
                "protein": 30,
                "carbs": 20,
                "fat": 35
            },
            "snack": {
                "meal": "Greek yogurt with nuts",
                "calories": 200,
                "protein": 15,
                "carbs": 10,
                "fat": 12
            }
        }
    
    # Adjust for dietary restrictions (very basic implementation)
    if "vegetarian" in form.dietary_restrictions:
        for day in meal_plan:
            meal_plan[day]["lunch"]["meal"] = "Quinoa bowl with roasted vegetables and tofu"
            meal_plan[day]["dinner"]["meal"] = "Vegetarian stir-fry with tempeh"
    
    # Create a shopping list
    shopping_list = [
        "Oats", "Protein powder", "Fruits", "Chicken breast", 
        "Mixed greens", "Avocado", "Salmon", "Vegetables for roasting",
        "Greek yogurt", "Mixed nuts"
    ]
    
    if "vegetarian" in form.dietary_restrictions:
        shopping_list.remove("Chicken breast")
        shopping_list.remove("Salmon")
        shopping_list.extend(["Tofu", "Tempeh", "Quinoa"])
    
    # Return the complete plan
    return {
        "user_profile": {
            "name": form.name,
            "caloric_target": caloric_target,
            "goal": form.goal,
            "dietary_restrictions": form.dietary_restrictions,
        },
        "meal_plan": meal_plan,
        "shopping_list": shopping_list,
        "daily_totals": {
            "calories": caloric_target,
            "protein": int(caloric_target * 0.25 / 4),  # 25% protein, 4 calories per gram
            "carbs": int(caloric_target * 0.45 / 4),    # 45% carbs, 4 calories per gram
            "fat": int(caloric_target * 0.3 / 9)        # 30% fat, 9 calories per gram
        },
        "note": "This is a mock meal plan generated for demonstration. The actual meal planner would use Strands agents."
    }

if __name__ == "__main__":
    app.run(host="127.0.0.1", port=8000, debug=True)